#ddev-gitpod-generated
router_http_port: 8080
router_https_port: 8443
use_dns_when_possible: false

additional_fqdns:
- 8080-bma1656-testdrupal-d8sbohda85t.ws-us106.gitpod.io
- 8025-bma1656-testdrupal-d8sbohda85t.ws-us106.gitpod.io
- 8036-bma1656-testdrupal-d8sbohda85t.ws-us106.gitpod.io
